class PassportPlace {
  final String id; // unik, ex: 'concubine_lane'
  final String name; // ex: 'Concubine Lane'
  final String region; // ex: 'Ipoh'
  final String category; // ex: 'Attraction'
  final String imageAsset; // asset path
  final double? lat;
  final double? lng;

  const PassportPlace({
    required this.id,
    required this.name,
    required this.region,
    required this.category,
    required this.imageAsset,
    this.lat,
    this.lng,
  });
}

const kPassportPlaces = [
  PassportPlace(
    id: 'concubine_lane',
    name: 'Concubine Lane',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/concubine_lane.jpg',
    lat: 4.5974,
    lng: 101.0789,
  ),
  PassportPlace(
    id: 'kellies_castle',
    name: 'Kellie\'s Castle',
    region: 'Batu Gajah',
    category: 'Attraction',
    imageAsset: 'assets/passport/kellies_castle.jpg',
    lat: 4.4763,
    lng: 101.0653,
  ),
  PassportPlace(
    id: 'ipoh_old_town',
    name: 'Ipoh Old Town',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/ipoh_old_town.jpg',
    lat: 4.5975,
    lng: 101.0758,
  ),
  PassportPlace(
    id: 'lost_world_of_tambun',
    name: 'Lost World of Tambun',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/lost_world_of_tambun.jpg',
    lat: 4.6186,
    lng: 101.1322,
  ),
  PassportPlace(
    id: 'sam_poh_tong',
    name: 'Sam Poh Tong Cave Temple',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/sam_poh_tong.jpg',
    lat: 4.5647,
    lng: 101.1147,
  ),
  PassportPlace(
    id: 'kek_lok_tong',
    name: 'Kek Lok Tong Cave Temple',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/kek_lok_tong.jpg',
    lat: 4.6186,
    lng: 101.1267,
  ),
  PassportPlace(
    id: 'birch_memorial',
    name: 'Birch Memorial Clock Tower',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/birch_memorial.jpg',
    lat: 4.5975,
    lng: 101.0758,
  ),
  PassportPlace(
    id: 'ipoh_railway_station',
    name: 'Ipoh Railway Station',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/ipoh_railway_station.jpg',
    lat: 4.5978,
    lng: 101.0745,
  ),
  PassportPlace(
    id: 'perak_cave_temple',
    name: 'Perak Cave Temple',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/perak_cave_temple.jpg',
    lat: 4.6422,
    lng: 101.1089,
  ),
  PassportPlace(
    id: 'ipoh_town_hall',
    name: 'Ipoh Town Hall',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/ipoh_town_hall.jpg',
    lat: 4.5956,
    lng: 101.0756,
  ),
  PassportPlace(
    id: 'royal_perak_museum',
    name: 'Perak Museum',
    region: 'Taiping',
    category: 'Attraction',
    imageAsset: 'assets/passport/royal_perak_museum.jpg',
    lat: 4.8525,
    lng: 100.7417,
  ),
  PassportPlace(
    id: 'taiping_lake_gardens',
    name: 'Taiping Lake Gardens',
    region: 'Taiping',
    category: 'Attraction',
    imageAsset: 'assets/passport/taiping_lake_gardens.jpg',
    lat: 4.8561,
    lng: 100.7311,
  ),
  PassportPlace(
    id: 'taiping_zoo',
    name: 'Taiping Zoo & Night Safari',
    region: 'Taiping',
    category: 'Attraction',
    imageAsset: 'assets/passport/taiping_zoo.jpg',
    lat: 4.8478,
    lng: 100.7308,
  ),
  PassportPlace(
    id: 'maxwell_hill',
    name: 'Maxwell Hill (Bukit Larut)',
    region: 'Taiping',
    category: 'Attraction',
    imageAsset: 'assets/passport/maxwell_hill.jpg',
    lat: 4.8761,
    lng: 100.7847,
  ),
  PassportPlace(
    id: 'perak_tong_cave',
    name: 'Perak Tong Cave Temple',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/perak_tong_cave.jpg',
    lat: 4.6422,
    lng: 101.1089,
  ),
  PassportPlace(
    id: 'gua_tempurung',
    name: 'Gua Tempurung',
    region: 'Gopeng',
    category: 'Attraction',
    imageAsset: 'assets/passport/gua_tempurung.jpg',
    lat: 4.4167,
    lng: 101.1667,
  ),
  PassportPlace(
    id: 'ubudiah_mosque',
    name: 'Ubudiah Mosque',
    region: 'Kuala Kangsar',
    category: 'Attraction',
    imageAsset: 'assets/passport/ubudiah_mosque.jpg',
    lat: 4.7681,
    lng: 100.9361,
  ),
  PassportPlace(
    id: 'royal_perak_mausoleum',
    name: 'Royal Perak Mausoleum',
    region: 'Kuala Kangsar',
    category: 'Attraction',
    imageAsset: 'assets/passport/royal_perak_mausoleum.jpg',
    lat: 4.7686,
    lng: 100.9367,
  ),
  PassportPlace(
    id: 'istana_kenangan',
    name: 'Istana Kenangan',
    region: 'Kuala Kangsar',
    category: 'Attraction',
    imageAsset: 'assets/passport/istana_kenangan.jpg',
    lat: 4.7744,
    lng: 100.9367,
  ),
  PassportPlace(
    id: 'han_chin_pet_soo',
    name: 'Han Chin Pet Soo Museum',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/han_chin_pet_soo.jpg',
    lat: 4.5956,
    lng: 101.0778,
  ),
  PassportPlace(
    id: 'teluk_batik_beach',
    name: 'Teluk Batik Beach',
    region: 'Lumut',
    category: 'Attraction',
    imageAsset: 'assets/passport/teluk_batik_beach.jpg',
    lat: 4.2347,
    lng: 100.6306,
  ),
  PassportPlace(
    id: 'pulau_pangkor',
    name: 'Pulau Pangkor',
    region: 'Pangkor',
    category: 'Attraction',
    imageAsset: 'assets/passport/pulau_pangkor.jpg',
    lat: 4.2167,
    lng: 100.5500,
  ),
  PassportPlace(
    id: 'darul_ridzuan_museum',
    name: 'Darul Ridzuan Museum',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/darul_ridzuan_museum.jpg',
    lat: 4.5975,
    lng: 101.0758,
  ),
  PassportPlace(
    id: 'gopeng_heritage_house',
    name: 'Gopeng Heritage House',
    region: 'Gopeng',
    category: 'Attraction',
    imageAsset: 'assets/passport/gopeng_heritage_house.jpg',
    lat: 4.4667,
    lng: 101.1667,
  ),
  PassportPlace(
    id: 'kinta_tin_mining',
    name: 'Kinta Tin Mining Museum',
    region: 'Kampar',
    category: 'Attraction',
    imageAsset: 'assets/passport/kinta_tin_mining.jpg',
    lat: 4.3000,
    lng: 101.1500,
  ),
  PassportPlace(
    id: 'taman_rekreasi_gunung_lang',
    name: 'Gunung Lang Recreational Park',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/taman_rekreasi_gunung_lang.jpg',
    lat: 4.6303,
    lng: 101.0928,
  ),
  PassportPlace(
    id: 'movie_animation_park',
    name: 'Movie Animation Park Studios',
    region: 'Ipoh',
    category: 'Attraction',
    imageAsset: 'assets/passport/movie_animation_park.jpg',
    lat: 4.5983,
    lng: 101.2506,
  ),
  PassportPlace(
    id: 'batu_gajah_museum',
    name: 'Batu Gajah Museum',
    region: 'Batu Gajah',
    category: 'Attraction',
    imageAsset: 'assets/passport/batu_gajah_museum.jpg',
    lat: 4.4667,
    lng: 101.0500,
  ),
  PassportPlace(
    id: 'menglembu_town',
    name: 'Menglembu Heritage Town',
    region: 'Menglembu',
    category: 'Attraction',
    imageAsset: 'assets/passport/menglembu_town.jpg',
    lat: 4.6333,
    lng: 101.1000,
  ),
  // Food places
  PassportPlace(
    id: 'nasi_ganja',
    name: 'Nasi Ganja',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/nasi_ganja.jpg',
    lat: 4.5975,
    lng: 101.0758,
  ),
  PassportPlace(
    id: 'ipoh_white_coffee',
    name: 'Ipoh White Coffee',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/ipoh_white_coffee.jpg',
    lat: 4.5975,
    lng: 101.0758,
  ),
  PassportPlace(
    id: 'tau_fu_fah',
    name: 'Funny Mountain Tau Fu Fah',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/tau_fu_fah.jpg',
    lat: 4.5989,
    lng: 101.0776,
  ),
  PassportPlace(
    id: 'thean_chun',
    name: 'Thean Chun Coffee Shop',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/thean_chun.jpg',
    lat: 4.5984,
    lng: 101.0769,
  ),
  PassportPlace(
    id: 'lou_wong_tauge_ayam',
    name: 'Lou Wong Tauge Ayam',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/lou_wong_tauge_ayam.jpg',
    lat: 4.5956,
    lng: 101.0789,
  ),
  PassportPlace(
    id: 'restoran_tauge_ayam_nga',
    name: 'Restoran Tauge Ayam Nga Choi Kai',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/tauge_ayam_nga.jpg',
    lat: 4.5956,
    lng: 101.0792,
  ),
  PassportPlace(
    id: 'ming_court_dim_sum',
    name: 'Ming Court Hong Kong Dim Sum',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/ming_court.jpg',
    lat: 4.5833,
    lng: 101.0833,
  ),
  PassportPlace(
    id: 'foh_san_dim_sum',
    name: 'Foh San Dim Sum',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/foh_san.jpg',
    lat: 4.5975,
    lng: 101.0758,
  ),
  PassportPlace(
    id: 'nam_heong_white_coffee',
    name: 'Nam Heong White Coffee',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/nam_heong.jpg',
    lat: 4.5967,
    lng: 101.0761,
  ),
  PassportPlace(
    id: 'sin_yoon_loong',
    name: 'Sin Yoon Loong White Coffee',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/sin_yoon_loong.jpg',
    lat: 4.5972,
    lng: 101.0765,
  ),
  PassportPlace(
    id: 'restoran_ipoh_kong_heng',
    name: 'Restoran Kong Heng',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/kong_heng.jpg',
    lat: 4.5978,
    lng: 101.0767,
  ),
  PassportPlace(
    id: 'ong_kee_tauge_ayam',
    name: 'Restoran Ong Kee Tauge Ayam',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/ong_kee.jpg',
    lat: 4.5961,
    lng: 101.0785,
  ),
  PassportPlace(
    id: 'wan_li_hong_ngau_lam_mee',
    name: 'Wan Li Hong Ngau Lam Mee',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/wan_li_hong.jpg',
    lat: 4.5950,
    lng: 101.0780,
  ),
  PassportPlace(
    id: 'yee_fatt_laksa',
    name: 'Yee Fatt Curry Mee & Laksa',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/yee_fatt_laksa.jpg',
    lat: 4.5980,
    lng: 101.0770,
  ),
  PassportPlace(
    id: 'plan_b_ipoh',
    name: 'Plan b Cafe',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/plan_b.jpg',
    lat: 4.5989,
    lng: 101.0778,
  ),
  PassportPlace(
    id: 'burps_and_giggles',
    name: 'Burps & Giggles',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/burps_giggles.jpg',
    lat: 4.5992,
    lng: 101.0782,
  ),
  PassportPlace(
    id: 'bits_bobs_cafe',
    name: 'Bits & Bobs Cafe',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/bits_bobs.jpg',
    lat: 4.5985,
    lng: 101.0775,
  ),
  PassportPlace(
    id: 'the_happy_8_ipoh',
    name: 'The Happy 8 Retreat',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/happy_8.jpg',
    lat: 4.5678,
    lng: 101.0989,
  ),
  PassportPlace(
    id: 'pusing_public_seafood',
    name: 'Pusing Public Seafood',
    region: 'Pusing',
    category: 'Food',
    imageAsset: 'assets/passport/pusing_seafood.jpg',
    lat: 4.5167,
    lng: 101.1500,
  ),
  PassportPlace(
    id: 'restoran_tuck_kee',
    name: 'Restoran Tuck Kee Ipoh',
    region: 'Ipoh',
    category: 'Food',
    imageAsset: 'assets/passport/tuck_kee.jpg',
    lat: 4.5970,
    lng: 101.0760,
  ),
  // Cafes
  PassportPlace(
    id: 'wunderbar_cafe',
    name: 'Wunderbar Cafe',
    region: 'Ipoh',
    category: 'Cafe',
    imageAsset: 'assets/passport/wunderbar.jpg',
    lat: 4.5988,
    lng: 101.0779,
  ),
  PassportPlace(
    id: 'thumbs_cafe',
    name: 'Thumbs Cafe',
    region: 'Ipoh',
    category: 'Cafe',
    imageAsset: 'assets/passport/thumbs_cafe.jpg',
    lat: 4.5975,
    lng: 101.0758,
  ),
  PassportPlace(
    id: 'yasmin_ipoh',
    name: 'Yasmin @ Kong Heng',
    region: 'Ipoh',
    category: 'Cafe',
    imageAsset: 'assets/passport/yasmin.jpg',
    lat: 4.5978,
    lng: 101.0767,
  ),
  PassportPlace(
    id: 'roquette_cafe',
    name: 'Roquette Cafe',
    region: 'Ipoh',
    category: 'Cafe',
    imageAsset: 'assets/passport/roquette.jpg',
    lat: 4.5983,
    lng: 101.0773,
  ),
  PassportPlace(
    id: 'leaf_co_cafe',
    name: 'Leaf & Co. Cafe',
    region: 'Ipoh',
    category: 'Cafe',
    imageAsset: 'assets/passport/leaf_co.jpg',
    lat: 4.5990,
    lng: 101.0780,
  ),
  PassportPlace(
    id: 'mirror_cafe',
    name: 'Mirror Cafe',
    region: 'Ipoh',
    category: 'Cafe',
    imageAsset: 'assets/passport/mirror_cafe.jpg',
    lat: 4.5986,
    lng: 101.0776,
  ),
  // Hotels
  PassportPlace(
    id: 'the_haven_resort',
    name: 'The Haven Resort Hotel',
    region: 'Ipoh',
    category: 'Hotel',
    imageAsset: 'assets/passport/haven_resort.jpg',
    lat: 4.6186,
    lng: 101.1322,
  ),
  PassportPlace(
    id: 'french_hotel_ipoh',
    name: 'The French Hotel',
    region: 'Ipoh',
    category: 'Hotel',
    imageAsset: 'assets/passport/french_hotel.jpg',
    lat: 4.5975,
    lng: 101.0758,
  ),
  PassportPlace(
    id: 'sekeping_kong_heng',
    name: 'Sekeping Kong Heng',
    region: 'Ipoh',
    category: 'Hotel',
    imageAsset: 'assets/passport/sekeping.jpg',
    lat: 4.5978,
    lng: 101.0767,
  ),
  PassportPlace(
    id: 'hotel_excelsior',
    name: 'Hotel Excelsior Ipoh',
    region: 'Ipoh',
    category: 'Hotel',
    imageAsset: 'assets/passport/excelsior.jpg',
    lat: 4.5953,
    lng: 101.0753,
  ),
  PassportPlace(
    id: 'the_banjaran_hotsprings',
    name: 'The Banjaran Hotsprings Retreat',
    region: 'Ipoh',
    category: 'Hotel',
    imageAsset: 'assets/passport/banjaran.jpg',
    lat: 4.6100,
    lng: 101.1450,
  ),
  PassportPlace(
    id: 'weil_hotel',
    name: 'Weil Hotel',
    region: 'Ipoh',
    category: 'Hotel',
    imageAsset: 'assets/passport/weil_hotel.jpg',
    lat: 4.5972,
    lng: 101.0764,
  ),
  PassportPlace(
    id: 'moty_hotel',
    name: 'M Boutique Hotel',
    region: 'Ipoh',
    category: 'Hotel',
    imageAsset: 'assets/passport/m_boutique.jpg',
    lat: 4.5980,
    lng: 101.0770,
  ),
  PassportPlace(
    id: 'pangkor_laut_resort',
    name: 'Pangkor Laut Resort',
    region: 'Pangkor',
    category: 'Hotel',
    imageAsset: 'assets/passport/pangkor_laut.jpg',
    lat: 4.1978,
    lng: 100.5492,
  ),
  // Places of Worship
  PassportPlace(
    id: 'st_michael_church',
    name: 'St. Michael\'s Institution Church',
    region: 'Ipoh',
    category: 'Worship',
    imageAsset: 'assets/passport/st_michael.jpg',
    lat: 4.5947,
    lng: 101.0742,
  ),
  PassportPlace(
    id: 'ipoh_tua_pek_kong',
    name: 'Tua Pek Kong Temple',
    region: 'Ipoh',
    category: 'Worship',
    imageAsset: 'assets/passport/tua_pek_kong.jpg',
    lat: 4.5961,
    lng: 101.0756,
  ),
  PassportPlace(
    id: 'cave_temple_enlightenment',
    name: 'Ling Sen Tong Cave Temple',
    region: 'Ipoh',
    category: 'Worship',
    imageAsset: 'assets/passport/ling_sen_tong.jpg',
    lat: 4.6200,
    lng: 101.1280,
  ),
  PassportPlace(
    id: 'nan_tian_tong',
    name: 'Nan Tian Tong Temple',
    region: 'Ipoh',
    category: 'Worship',
    imageAsset: 'assets/passport/nan_tian_tong.jpg',
    lat: 4.6150,
    lng: 101.1250,
  ),
  PassportPlace(
    id: 'shri_subramaniar_temple',
    name: 'Shri Subramaniar Swamy Temple',
    region: 'Batu Caves',
    category: 'Worship',
    imageAsset: 'assets/passport/subramaniar.jpg',
    lat: 4.6333,
    lng: 101.1167,
  ),
  PassportPlace(
    id: 'masjid_panglima_kinta',
    name: 'Masjid Panglima Kinta',
    region: 'Ipoh',
    category: 'Worship',
    imageAsset: 'assets/passport/panglima_kinta.jpg',
    lat: 4.5961,
    lng: 101.0750,
  ),
  PassportPlace(
    id: 'masjid_india_ipoh',
    name: 'Masjid India Muslim Ipoh',
    region: 'Ipoh',
    category: 'Worship',
    imageAsset: 'assets/passport/masjid_india.jpg',
    lat: 4.5958,
    lng: 101.0753,
  ),
  PassportPlace(
    id: 'st_john_church',
    name: 'Church of St. John the Baptist',
    region: 'Batu Gajah',
    category: 'Worship',
    imageAsset: 'assets/passport/st_john.jpg',
    lat: 4.4667,
    lng: 101.0500,
  ),
  // Shopping & Markets
  PassportPlace(
    id: 'ipoh_parade',
    name: 'Ipoh Parade Shopping Mall',
    region: 'Ipoh',
    category: 'Shopping',
    imageAsset: 'assets/passport/ipoh_parade.jpg',
    lat: 4.5947,
    lng: 101.0889,
  ),
  PassportPlace(
    id: 'kinta_city',
    name: 'Kinta City Shopping Centre',
    region: 'Ipoh',
    category: 'Shopping',
    imageAsset: 'assets/passport/kinta_city.jpg',
    lat: 4.5900,
    lng: 101.0861,
  ),
  PassportPlace(
    id: 'ipoh_old_town_market',
    name: 'Ipoh Old Town Morning Market',
    region: 'Ipoh',
    category: 'Shopping',
    imageAsset: 'assets/passport/morning_market.jpg',
    lat: 4.5975,
    lng: 101.0758,
  ),
  PassportPlace(
    id: 'pasar_besar_ipoh',
    name: 'Pasar Besar Bulatan Ipoh',
    region: 'Ipoh',
    category: 'Shopping',
    imageAsset: 'assets/passport/pasar_besar.jpg',
    lat: 4.5986,
    lng: 101.0767,
  ),
];